[package]
name = "tsp3"
version = "0.1.0"
authors = ["Willi Kappler, grandor@gmx.de"]

[dependencies]
time = "0.1"
rand = "0.3"
simplelog = "0.4"
clap = "2.19"

darwin-rs = {path = "../../../darwin-rs"}

[profile.release]
lto = true
